default_platform(:ios)

platform :ios do

  slack_hook = "https://hooks.slack.com/services/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"

  lane :register_app do
    produce(
      username: "forwindsun1359@gmail.com",
      app_identifier: "com.razeware.chewchew1987",
      app_name: "chewchew1987",
      team_name: "WEI-TSUNG CHENG",
      itc_team_name: "WEI-TSUNG CHENG"
    )
  end

  # lane :sandbox_cert do 
  #   cert(
  #     username: "forwindsun1359@gmail.com",
  #     team_name: "WEI-TSUNG CHENG",
  #     development: true
  #   )
  # end

  # lane :sandbox_sigh do
  #   sigh(
  #     username: "forwindsun1359@gmail.com",
  #     team_name: "WEI-TSUNG CHENG",
  #     app_identifier: "com.razeware.chewchew1987",
  #     development: true
  #   )
  # end

  lane :get_dev_cert_and_sign do
    cert(development: true)
    sigh(development: true)
  end

  
  desc "Update iOS UDID's on the Developer Portal"
  lane :sync_device_info do
    register_devices(
      devices_file: "fastlane/Devicefile"
      )
  end

  desc "Sync team Code-Signing assets"
  lane :sync_signing_assets do |options| 
    sync_device_info
    selectedType = options[:type]
    match(type: selectedType)
  end



  # desc "Re-obtain match code-signing credentials after switching to a Beginning or Ending project folder"
  # lane :bootstrap_code_signing do
  #   sync_device_info
  #   match(type: "development")
  #   match(type: "adhoc")
  #   match(type: "appstore")
  # end


  # lane :sandbox do
  #   gym(
  #     scheme: "ChewChewTrain",
  #     output_directory: "build_AdHoc",
  #     export_method: "ad-hoc",
  #     export_options: {
  #       provisioningProfiles: {
  #         "com.razeware.chewchew1987" => "match AdHoc com.razeware.chewchew1987"
  #       }
  #     }
  #   )
  # end

  desc "Build for App Store submission"
  lane :build_appstore do
    ensure_git_status_clean
    ensure_git_branch(branch: "stage")
    git_pull


    sync_signing_assets(type: "appstore")

    scan(
      devices: ["iPhone 12"]
    )
    lint
    document

    increment_build_number
    gym(
      output_directory: "build_Appstore",
      export_method: "app-store"
    )

    commit_version_bump(
      force: true,
      message: "Version bumped by fastlane"
    )

    add_git_tag(
      grouping: "fastlane",
      build_number: lane_context[SharedValues::BUILD_NUMBER]
    )

    push_to_git_remote

    v = lane_context[SharedValues::VERSION_NUMBER]
    b = lane_context[SharedValues::BUILD_NUMBER]
    d = sh "date -u"

    slack(
      payload: {"FASTLANE PRODUCTION - #{v}(#{b})" => d},
      slack_url: slack_hook
    )


  end


  desc "Build for Ad Hoc submission"
  lane :build_adhoc do
    ensure_git_status_clean
    ensure_git_branch(branch: "stage")
    git_pull

    sync_signing_assets(type: "adhoc")

    scan(
      devices: ["iPhone 12"]
    )
    lint
    document

    increment_build_number
    gym(
      output_directory: "build_AdHoc",
      export_method: "ad-hoc"
    )
  end

  # lane :sandbox_pilot do 
  #   pilot
  # end

  lane :distribute_to_appstore do
    build_appstore
    pilot(
      ipa: "./build_Appstore/ChewChewTrain.ipa",
      team_name: "WEI-TSUNG CHENG",
      changelog: "Version {lane_context[SharedValues::VERSION_NUMBER]}, Build {lane_context[SharedValues::BUILD_NUMBER]}"
    )
  end

  lane :distribute_to_installer do
    build_adhoc
    installr(
      api_token: "k6IicYC0Q4ygRi6sj2OWAVtOZ6k7aHX0",
      ipa: "./build_AdHoc/ChewChewTrain.ipa",
      notes: "Version {lane_context[SharedValues::VERSION_NUMBER]}, Build {lane_context[SharedValues::BUILD_NUMBER]}"
    )
  end


  lane :release do 
    precheck
    build_appstore
  #  UI.success "Still running"
    snapshot
    frameit(gold: true)
    deliver(
      ipa: "./build_Appstore/ChewChewTrain.ipa",
      run_precheck_before_submit: false,
      force: true,
      team_name: "WEI-TSUNG CHENG"
    )
  end

  # lane :sandbox do
  #   frameit(path: "./fastlane/screenshots")
  # end


  # lane :sandbox do
  #   deliver( 
  #     ipa: "./build_Appstore/ChewChewTrain.ipa",
  #     force: true,
  #     submit_for_review: true
  #   )
  # end


  lane :lint do
    swiftlint(
    mode: :autocorrect,
      config_file: ".swiftlint.yml",
      output_file: "swiftlintOutput.txt",
      ignore_exit_status: false
    )
  end

  lane :document do
    jazzy config: "./fastlane/jazzy.yaml"
  end


  lane :ping_slack do

    slack(
      message: "Hello I am fastlane From Me John",
      slack_url: slack_hook,
      default_payloads: [],
      payload: {"John" => "Hello Picka"}
    )
  end 

end

