# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from

devices([
  "iPhone 12",
  "iPhone 13 Pro"
])


languages([
    "en-US",
    "de-DE"
])

scheme("FastlaneSnapshots")

skip_open_summary true 
stop_after_first_error true 
erase_simulator true 
clear_previous_screenshots true 
reinstall_app true
